services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - sentiment-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sentiment-network

networks:
  sentiment-network:
    driver: bridge